name: "Dependabot Auto Merge"

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  dependabot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Dependabot Metadata
        id: metadata
        uses: dependabot/fetch-metadata@v1

      - name: Auto-merge Dependabot PRs
        if: ${{ steps.metadata.outputs.dependency-type == 'direct' }}
        run: gh pr merge --auto --squash "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
